### ISSUE TITLE
cannot install from npm [windows]

### ISSUE THREAD

**Issue by istian** [bessdsv/karma-jasmine-jquery#8]
hi Guys,

I'm trying to install this package via npm but have no luck. it always say can't connect to github. I have my git config global set to use https instead of git protocol and in fact npm install other packages works only this package. Am I missing something? or is there any workaround on this aside from direct cloning?

Thanks

**Comment by j4ys0n** [comment]
were you able to resolve this?

**Comment by dropofwill** [comment]
This is probably related to issue #3, there is a git dependency to Bessdsv's fork of bower-installer, which (as far as I can tell) is no longer necessary given the resolution of the issue upstream in [blittle/bower-installer](https://github.com/blittle/bower-installer/) via PR's [62](https://github.com/blittle/bower-installer/pull/62) and [101](https://github.com/blittle/bower-installer/pull/101).

My solution (issue with an internal firewall) was to publish a fork without that dependency internally and so far that seems to be working fine.

**Comment by sava1192** [comment]
same problem on Windows 7. log:
```
$ npm install karma-jasmine-jquery
npm WARN package.json @ No description
npm WARN package.json @ No repository field.
npm WARN package.json @ No README data
npm WARN package.json karma-remote-reporter@0.1.5 No repository field.
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/bessdsv/bower-
installer.git)
npm ERR! git clone git://github.com/bessdsv/bower-installer.git Cloning into bare repository 'C:\Use
rs\user\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-g
it-a4812cf9'...
npm ERR! git clone git://github.com/bessdsv/bower-installer.git fatal: unable to connect to github.c
om:
npm ERR! git clone git://github.com/bessdsv/bower-installer.git github.com[0: 192.30.252.131]: errno
=No error
npm ERR! Error: Command failed: Cloning into bare repository 'C:\Users\user\AppData\Roa
ming\npm-cache\_git-remotes\git-github-com-bessdsv-bower-installer-git-a4812cf9'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.131]: errno=No error
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:755:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:822:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "c:\\Program Files\\nodejs\\node.exe" "c:\\Program Files\\nodejs\\node_modules\\npm
\\bin\\npm-cli.js" "install" "karma-jasmine-jquery"
npm ERR! cwd d:\some\folder
npm ERR! node -v v0.10.29
npm ERR! npm -v 1.4.14
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     d:\some\folder\npm-debug.log
npm ERR! not ok code 0
```

**Comment by mali2602** [comment]
I am having the same issue on windows 7 too.

npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/bessdsv/bower-installer.git) undefined
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/bessdsv/bower-installer.git) undefined
npm ERR! git clone git://github.com/bessdsv/bower-installer.git undefined
npm ERR! git clone git://github.com/bessdsv/bower-installer.git undefined
npm ERR! not found: git
npm ERR!
npm ERR! Failed using git.
npm ERR! This is most likely not a problem with npm itself.
npm ERR! Please check if you have git installed and in your PATH.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"

**Comment by sandwichsudo** [comment]
I have this issue on OSX as well

**Comment by AStoker** [comment]
Since the pull request to fix the issue has been sitting untouched for months, a fork has been made with the fix. See details here: https://github.com/bessdsv/karma-jasmine-jquery/pull/10 Branch here: https://github.com/AStoker/karma-jasmine-jquery/ 

Via npm and Bower, it was registered under the name `karma-jasmine-jquery-2` to avoid naming conflicts, but can also be installed via JSPM just fine. Unfortunate that it came to this, but it has been causing trouble for some time now.
